package org.minecraftprot.stackframe.diagnostic.registry;

import java.util.Arrays;
import java.util.Comparator;
import java.util.stream.Collectors;

/** Deterministic Markdown projection of the canonical registry. */
public final class RegistryCatalogGenerator {
    private RegistryCatalogGenerator() {
    }

    public static String generate(DiagnosticRegistrySnapshot registry) {
        RegistryValidation.required(registry, "registry");
        var output = new StringBuilder();
        output.append("""
                <!-- Generated by :stackframe-core:generateDiagnosticRegistryCatalog. Do not edit. -->
                # Diagnostic code catalog

                The canonical source is `CanonicalDiagnosticRegistry`. Registry validation and
                compatibility policy are documented in [README.md](README.md).

                ## Allocated ranges

                | Range | Area | Registered | Available |
                | --- | --- | ---: | ---: |
                """);
        for (var area : DiagnosticArea.values()) {
            var registered = registry.entries().stream()
                    .filter(entry -> entry.area() == area)
                    .count();
            output.append("| `")
                    .append(area.range())
                    .append("` | ")
                    .append(area.displayName())
                    .append(" | ")
                    .append(registered)
                    .append(" | ")
                    .append(registry.availableCodes(area).size())
                    .append(" |\n");
        }
        output.append("\n## Lifecycle summary\n\n");
        for (var lifecycle : DiagnosticLifecycle.values()) {
            output.append("- **")
                    .append(lifecycle)
                    .append(":** ")
                    .append(registry.entries(lifecycle).size())
                    .append("\n");
        }
        output.append("\n## Governed arbitration metadata\n\n");
        if (registry.classifiers().isEmpty()) {
            output.append("No classifier registrations are allocated.\n");
        } else {
            output.append("""
                    | Classifier key | Diagnostic | Precedence | Combination |
                    | --- | --- | ---: | --- |
                    """);
            for (var classifier : registry.classifiers()) {
                output.append("| `")
                        .append(classifier.classifierKey())
                        .append("` | `")
                        .append(classifier.diagnosticCode().value())
                        .append("` | ")
                        .append(classifier.precedence())
                        .append(" | `")
                        .append(classifier.combinationPolicy())
                        .append("` |\n");
            }
        }
        output.append("""

                ### Combination policies

                | Policy | Meaning |
                | --- | --- |
                """);
        Arrays.stream(CombinationPolicy.values())
                .sorted(Comparator.comparing(Enum::name))
                .forEach(policy -> output.append("| `")
                        .append(policy)
                        .append("` | ")
                        .append(policy.meaning())
                        .append(" |\n"));
        output.append("""

                ### Arbitration reason codes

                | Reason code | Applies to | Meaning |
                | --- | --- | --- |
                """);
        Arrays.stream(ArbitrationReasonCode.values())
                .sorted(Comparator.comparing(ArbitrationReasonCode::key))
                .forEach(reason -> output.append("| `")
                        .append(reason.key())
                        .append("` | `")
                        .append(reason.scope())
                        .append("` | ")
                        .append(reason.meaning())
                        .append(" |\n"));
        output.append("\n### Reason assignment contract\n\n")
                .append("`")
                .append(ArbitrationReasonAssignment.CONTRACT_ID)
                .append("`: ")
                .append(ArbitrationReasonAssignment.CONTRACT)
                .append("\n");
        output.append("""

                ## Governed remediation actions

                | Action | Safety | Remedy evidence | Confirmation | Backup | Meaning |
                | --- | --- | --- | --- | --- | --- |
                """);
        Arrays.stream(RemediationAction.values())
                .sorted(Comparator.comparing(Enum::name))
                .forEach(action -> output.append("| `")
                        .append(action)
                        .append("` | `")
                        .append(action.safety())
                        .append("` | ")
                        .append(action.requiresRemedyEvidence())
                        .append(" | ")
                        .append(action.requiresOperatorConfirmation())
                        .append(" | ")
                        .append(action.requiresBackup())
                        .append(" | ")
                        .append(action.meaning())
                        .append(" |\n"));
        for (var entry : registry.entries()) {
            var capabilities = entry.evidence().capabilities().stream()
                    .sorted(Comparator.comparing(Enum::name))
                    .map(capability -> "`" + capability + "`")
                    .collect(Collectors.joining(", "));
            var actions = entry.remediation().actions().stream()
                    .sorted(Comparator.comparing(Enum::name))
                    .map(action -> "`" + action + "`")
                    .collect(Collectors.joining(", "));
            output.append("\n<a id=\"")
                    .append(entry.documentationAnchor())
                    .append("\"></a>\n## ")
                    .append(entry.code().value())
                    .append(" - ")
                    .append(entry.title().value())
                    .append("\n\n")
                    .append("- **Symbolic key:** `")
                    .append(entry.symbolicKey())
                    .append("`\n- **Area:** ")
                    .append(entry.area().displayName())
                    .append("\n- **Owner:** `")
                    .append(entry.owner())
                    .append("`\n- **Lifecycle:** `")
                    .append(entry.lifecycle())
                    .append("`\n- **Meaning:** ")
                    .append(entry.meaning())
                    .append("\n- **Required evidence:** ")
                    .append(entry.evidence().description())
                    .append("\n- **Evidence capabilities:** ")
                    .append(capabilities)
                    .append("\n- **Fallback:** ")
                    .append(entry.fallback().description())
                    .append(" (`")
                    .append(entry.fallback().fallbackCode().value())
                    .append("`)\n- **Remediation actions:** ")
                    .append(actions)
                    .append("\n- **Remediation safety:** `")
                    .append(entry.remediation().safety())
                    .append("` - ")
                    .append(entry.remediation().explanation())
                    .append("\n");
        }
        return output.toString();
    }

    public static void verify(DiagnosticRegistrySnapshot registry, String committedCatalog) {
        RegistryValidation.required(committedCatalog, "committedCatalog");
        if (!generate(registry).equals(committedCatalog.replace("\r\n", "\n"))) {
            throw new RegistryValidationException(
                    "generated diagnostic catalog drifted; run "
                            + ":stackframe-core:generateDiagnosticRegistryCatalog");
        }
    }
}
