package org.minecraftprot.stackframe.diagnostic.registry;

import java.util.Comparator;
import java.util.stream.Collectors;

/** Deterministic Markdown projection of the canonical registry. */
public final class RegistryCatalogGenerator {
    private RegistryCatalogGenerator() {
    }

    public static String generate(DiagnosticRegistrySnapshot registry) {
        RegistryValidation.required(registry, "registry");
        var output = new StringBuilder();
        output.append("""
                <!-- Generated by :stackframe-core:generateDiagnosticRegistryCatalog. Do not edit. -->
                # Diagnostic code catalog

                The canonical source is `CanonicalDiagnosticRegistry`. Registry validation and
                compatibility policy are documented in [README.md](README.md).

                ## Allocated ranges

                | Range | Area | Registered | Available |
                | --- | --- | ---: | ---: |
                """);
        for (var area : DiagnosticArea.values()) {
            var registered = registry.entries().stream()
                    .filter(entry -> entry.area() == area)
                    .count();
            output.append("| `")
                    .append(area.range())
                    .append("` | ")
                    .append(area.displayName())
                    .append(" | ")
                    .append(registered)
                    .append(" | ")
                    .append(registry.availableCodes(area).size())
                    .append(" |\n");
        }
        output.append("\n## Lifecycle summary\n\n");
        for (var lifecycle : DiagnosticLifecycle.values()) {
            output.append("- **")
                    .append(lifecycle)
                    .append(":** ")
                    .append(registry.entries(lifecycle).size())
                    .append("\n");
        }
        for (var entry : registry.entries()) {
            var capabilities = entry.evidence().capabilities().stream()
                    .sorted(Comparator.comparing(Enum::name))
                    .map(capability -> "`" + capability + "`")
                    .collect(Collectors.joining(", "));
            output.append("\n<a id=\"")
                    .append(entry.documentationAnchor())
                    .append("\"></a>\n## ")
                    .append(entry.code().value())
                    .append(" - ")
                    .append(entry.title().value())
                    .append("\n\n")
                    .append("- **Symbolic key:** `")
                    .append(entry.symbolicKey())
                    .append("`\n- **Area:** ")
                    .append(entry.area().displayName())
                    .append("\n- **Owner:** `")
                    .append(entry.owner())
                    .append("`\n- **Lifecycle:** `")
                    .append(entry.lifecycle())
                    .append("`\n- **Meaning:** ")
                    .append(entry.meaning())
                    .append("\n- **Required evidence:** ")
                    .append(entry.evidence().description())
                    .append("\n- **Evidence capabilities:** ")
                    .append(capabilities)
                    .append("\n- **Fallback:** ")
                    .append(entry.fallback().description())
                    .append(" (`")
                    .append(entry.fallback().fallbackCode().value())
                    .append("`)\n- **Remediation safety:** `")
                    .append(entry.remediation().safety())
                    .append("` - ")
                    .append(entry.remediation().description())
                    .append("\n");
        }
        return output.toString();
    }

    public static void verify(DiagnosticRegistrySnapshot registry, String committedCatalog) {
        RegistryValidation.required(committedCatalog, "committedCatalog");
        if (!generate(registry).equals(committedCatalog.replace("\r\n", "\n"))) {
            throw new RegistryValidationException(
                    "generated diagnostic catalog drifted; run "
                            + ":stackframe-core:generateDiagnosticRegistryCatalog");
        }
    }
}
